changeLogFile=db.changelog-master.yaml
url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
username=postgres.jhpcifbntjoclvxdfnpr
password=equipACodldldl34+_7
driver=org.postgresql.Driver
classpath=lib/postgresql-42.7.10.jar