-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 10:31
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/010_crear_tabla_lenguaje_alias.yaml::009-crear-tabla-lenguaje-alias::ibai
CREATE TABLE public.lenguaje_alias (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lenguaje_id SMALLINT NOT NULL, alias VARCHAR(100) NOT NULL, alias_normalizado VARCHAR(100) NOT NULL, CONSTRAINT lenguaje_alias_pkey PRIMARY KEY (id));

ALTER TABLE public.lenguaje_alias ADD CONSTRAINT fk_lenguaje_alias_lenguaje FOREIGN KEY (lenguaje_id) REFERENCES public.lenguaje (id) ON DELETE CASCADE;

ALTER TABLE public.lenguaje_alias ADD CONSTRAINT uk_lenguaje_alias_normalizado UNIQUE (alias_normalizado);

CREATE INDEX idx_lenguaje_alias_lenguaje ON public.lenguaje_alias(lenguaje_id);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('009-crear-tabla-lenguaje-alias', 'ibai', 'incremental/incremental/010_crear_tabla_lenguaje_alias.yaml', NOW(), 12, '9:48bd7b624485ee60864fa85e48b66350', 'createTable tableName=lenguaje_alias; addForeignKeyConstraint baseTableName=lenguaje_alias, constraintName=fk_lenguaje_alias_lenguaje, referencedTableName=lenguaje; addUniqueConstraint constraintName=uk_lenguaje_alias_normalizado, tableName=lengua...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6069065895');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

