-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 10:41
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/011_corregir_tipados_a_smallint.yaml::010-corregir-tipados-a-smallint::ibai
ALTER TABLE public.lenguaje DROP CONSTRAINT fk_lenguaje_tipado_tiempo;

ALTER TABLE public.lenguaje DROP CONSTRAINT fk_lenguaje_fortaleza_tipado;

DROP INDEX public.idx_lenguaje_tipado_tiempo;

DROP INDEX public.idx_lenguaje_fortaleza_tipado;

ALTER TABLE public.lenguaje DROP COLUMN tipado_tiempo_id;

ALTER TABLE public.lenguaje DROP COLUMN fortaleza_tipado_id;

DROP TABLE public.lenguaje_alias;

DROP TABLE public.tipado_tiempo;

DROP TABLE public.fortaleza_tipado;

CREATE TABLE public.tipado_tiempo (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(50) NOT NULL, CONSTRAINT tipado_tiempo_pkey PRIMARY KEY (id), UNIQUE (nombre));

CREATE TABLE public.fortaleza_tipado (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(50) NOT NULL, CONSTRAINT fortaleza_tipado_pkey PRIMARY KEY (id), UNIQUE (nombre));

INSERT INTO public.tipado_tiempo (nombre) VALUES ('Estatico');

INSERT INTO public.tipado_tiempo (nombre) VALUES ('Dinamico');

INSERT INTO public.fortaleza_tipado (nombre) VALUES ('Fuerte');

INSERT INTO public.fortaleza_tipado (nombre) VALUES ('Debil');

ALTER TABLE public.lenguaje ADD tipado_tiempo_id SMALLINT;

ALTER TABLE public.lenguaje ADD fortaleza_tipado_id SMALLINT;

ALTER TABLE public.lenguaje ALTER COLUMN  tipado_tiempo_id SET NOT NULL;

ALTER TABLE public.lenguaje ALTER COLUMN  fortaleza_tipado_id SET NOT NULL;

ALTER TABLE public.lenguaje ADD CONSTRAINT fk_lenguaje_tipado_tiempo FOREIGN KEY (tipado_tiempo_id) REFERENCES public.tipado_tiempo (id) ON DELETE RESTRICT;

ALTER TABLE public.lenguaje ADD CONSTRAINT fk_lenguaje_fortaleza_tipado FOREIGN KEY (fortaleza_tipado_id) REFERENCES public.fortaleza_tipado (id) ON DELETE RESTRICT;

CREATE INDEX idx_lenguaje_tipado_tiempo ON public.lenguaje(tipado_tiempo_id);

CREATE INDEX idx_lenguaje_fortaleza_tipado ON public.lenguaje(fortaleza_tipado_id);

CREATE TABLE public.lenguaje_alias (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lenguaje_id SMALLINT NOT NULL, alias VARCHAR(100) NOT NULL, alias_normalizado VARCHAR(100) NOT NULL, CONSTRAINT lenguaje_alias_pkey PRIMARY KEY (id));

ALTER TABLE public.lenguaje_alias ADD CONSTRAINT fk_lenguaje_alias_lenguaje FOREIGN KEY (lenguaje_id) REFERENCES public.lenguaje (id) ON DELETE CASCADE;

ALTER TABLE public.lenguaje_alias ADD CONSTRAINT uk_lenguaje_alias_normalizado UNIQUE (alias_normalizado);

CREATE INDEX idx_lenguaje_alias_lenguaje ON public.lenguaje_alias(lenguaje_id);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('010-corregir-tipados-a-smallint', 'ibai', 'incremental/incremental/011_corregir_tipados_a_smallint.yaml', NOW(), 13, '9:2c01be356141097b649d109f5dc895ef', 'dropForeignKeyConstraint baseTableName=lenguaje, constraintName=fk_lenguaje_tipado_tiempo; dropForeignKeyConstraint baseTableName=lenguaje, constraintName=fk_lenguaje_fortaleza_tipado; dropIndex indexName=idx_lenguaje_tipado_tiempo, tableName=leng...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6069685547');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

