-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 11:04
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/012_crear_tabla_reto_codigo.yaml::011-crear-tabla-reto-codigo::ibai
CREATE TABLE public.reto_codigo (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lenguaje_id SMALLINT NOT NULL, titulo VARCHAR(150) NOT NULL, snippet TEXT NOT NULL, salida_esperada TEXT NOT NULL, explicacion TEXT, activo BOOLEAN DEFAULT TRUE NOT NULL, CONSTRAINT reto_codigo_pkey PRIMARY KEY (id));

ALTER TABLE public.reto_codigo ADD CONSTRAINT fk_reto_codigo_lenguaje FOREIGN KEY (lenguaje_id) REFERENCES public.lenguaje (id) ON DELETE CASCADE;

CREATE INDEX idx_reto_codigo_lenguaje ON public.reto_codigo(lenguaje_id);

CREATE INDEX idx_reto_codigo_activo ON public.reto_codigo(activo);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('011-crear-tabla-reto-codigo', 'ibai', 'incremental/incremental/012_crear_tabla_reto_codigo.yaml', NOW(), 14, '9:c3f08a3d7e36d13feda784396525ebae', 'createTable tableName=reto_codigo; addForeignKeyConstraint baseTableName=reto_codigo, constraintName=fk_reto_codigo_lenguaje, referencedTableName=lenguaje; createIndex indexName=idx_reto_codigo_lenguaje, tableName=reto_codigo; createIndex indexNam...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6071091324');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

