-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 11:08
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/013_crear_tabla_partida.yaml::012-crear-tabla-partida::ibai
CREATE TABLE public.partida (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuario_id SMALLINT NOT NULL, modo VARCHAR(20) NOT NULL, lenguaje_objetivo_id SMALLINT, reto_codigo_id SMALLINT, estado VARCHAR(20) DEFAULT 'en_curso' NOT NULL, fase_actual VARCHAR(20) DEFAULT 'lenguaje' NOT NULL, max_intentos SMALLINT DEFAULT 6 NOT NULL, intentos_usados SMALLINT DEFAULT 0 NOT NULL, puntuacion INTEGER DEFAULT 0 NOT NULL, iniciada_en TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, finalizada_en TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT partida_pkey PRIMARY KEY (id));

ALTER TABLE public.partida ADD CONSTRAINT fk_partida_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario (id) ON DELETE CASCADE;

ALTER TABLE public.partida ADD CONSTRAINT fk_partida_lenguaje_objetivo FOREIGN KEY (lenguaje_objetivo_id) REFERENCES public.lenguaje (id) ON DELETE SET NULL;

ALTER TABLE public.partida ADD CONSTRAINT fk_partida_reto_codigo FOREIGN KEY (reto_codigo_id) REFERENCES public.reto_codigo (id) ON DELETE SET NULL;

CREATE INDEX idx_partida_usuario ON public.partida(usuario_id);

CREATE INDEX idx_partida_modo ON public.partida(modo);

CREATE INDEX idx_partida_estado ON public.partida(estado);

CREATE INDEX idx_partida_lenguaje_objetivo ON public.partida(lenguaje_objetivo_id);

CREATE INDEX idx_partida_reto_codigo ON public.partida(reto_codigo_id);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('012-crear-tabla-partida', 'ibai', 'incremental/incremental/013_crear_tabla_partida.yaml', NOW(), 15, '9:a3a8b6c95e41feba9877b7db5f772163', 'createTable tableName=partida; addForeignKeyConstraint baseTableName=partida, constraintName=fk_partida_usuario, referencedTableName=usuario; addForeignKeyConstraint baseTableName=partida, constraintName=fk_partida_lenguaje_objetivo, referencedTab...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6071322051');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

