-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 11:16
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/014_crear_tabla_intento_lenguaje.yaml::013-crear-tabla-intento-lenguaje::ibai
CREATE TABLE public.intento_lenguaje (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, partida_id SMALLINT NOT NULL, numero_intento SMALLINT NOT NULL, lenguaje_intentado_id SMALLINT NOT NULL, es_correcto BOOLEAN NOT NULL, feedback_json TEXT, creado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT intento_lenguaje_pkey PRIMARY KEY (id));

ALTER TABLE public.intento_lenguaje ADD CONSTRAINT fk_intento_lenguaje_partida FOREIGN KEY (partida_id) REFERENCES public.partida (id) ON DELETE CASCADE;

ALTER TABLE public.intento_lenguaje ADD CONSTRAINT fk_intento_lenguaje_lenguaje FOREIGN KEY (lenguaje_intentado_id) REFERENCES public.lenguaje (id) ON DELETE RESTRICT;

ALTER TABLE public.intento_lenguaje ADD CONSTRAINT uk_intento_lenguaje_partida_numero UNIQUE (partida_id, numero_intento);

CREATE INDEX idx_intento_lenguaje_partida ON public.intento_lenguaje(partida_id);

CREATE INDEX idx_intento_lenguaje_lenguaje ON public.intento_lenguaje(lenguaje_intentado_id);

CREATE INDEX idx_intento_lenguaje_correcto ON public.intento_lenguaje(es_correcto);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('013-crear-tabla-intento-lenguaje', 'ibai', 'incremental/incremental/014_crear_tabla_intento_lenguaje.yaml', NOW(), 16, '9:c94b708c36d147ee2f36883cf48262d2', 'createTable tableName=intento_lenguaje; addForeignKeyConstraint baseTableName=intento_lenguaje, constraintName=fk_intento_lenguaje_partida, referencedTableName=partida; addForeignKeyConstraint baseTableName=intento_lenguaje, constraintName=fk_inte...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6071777408');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

