-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ibai (192.168.1.187)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db.changelog-master.yaml
-- Ran at: 13/4/26, 11:19
-- Against: postgres.jhpcifbntjoclvxdfnpr@jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset incremental/incremental/015_crear_tabla_intento_codigo.yaml::014-crear-tabla-intento-codigo::ibai
CREATE TABLE public.intento_codigo (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, partida_id SMALLINT NOT NULL, numero_intento SMALLINT NOT NULL, respuesta_usuario TEXT NOT NULL, respuesta_normalizada TEXT, es_correcto BOOLEAN NOT NULL, creado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT intento_codigo_pkey PRIMARY KEY (id));

ALTER TABLE public.intento_codigo ADD CONSTRAINT fk_intento_codigo_partida FOREIGN KEY (partida_id) REFERENCES public.partida (id) ON DELETE CASCADE;

ALTER TABLE public.intento_codigo ADD CONSTRAINT uk_intento_codigo_partida_numero UNIQUE (partida_id, numero_intento);

CREATE INDEX idx_intento_codigo_partida ON public.intento_codigo(partida_id);

CREATE INDEX idx_intento_codigo_correcto ON public.intento_codigo(es_correcto);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('014-crear-tabla-intento-codigo', 'ibai', 'incremental/incremental/015_crear_tabla_intento_codigo.yaml', NOW(), 17, '9:f9531eefd6d8c413a96d0513691efe96', 'createTable tableName=intento_codigo; addForeignKeyConstraint baseTableName=intento_codigo, constraintName=fk_intento_codigo_partida, referencedTableName=partida; addUniqueConstraint constraintName=uk_intento_codigo_partida_numero, tableName=inten...', '', 'EXECUTED', NULL, NULL, '5.0.2', '6071945682');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

